### PR TITLE
Lua Run Selected Lines Fix

### LINKED ISSUE #394: Run Selection for LUA doesn't work
When trying to run selected text for LUA it only says "[Finished in 0.062s]" but doesn't display any actual code execution. To get code execution to display I have to run the entire file.

### PR DESCRIPTION
**Pull request by ThiconZ**
Fixes #394, Run Selected Line(s) for Lua, by creating a temp file with the
selected lines and prepending blank lines to the temp file equal to the
number of lines above the selected source lines to match Lua error lines
numbers from the temp file with those of the source view.

### CODE REVIEW

File: lib/grammars.coffee [hunk 1]
```diff
@@ -199,11 +202,6 @@ module.exports =
         command: "bash"
         args: (context) -> ['-c', "xcrun clang++ -fcolor-diagnostics -Wc++11-extensions -Wall -include stdio.h -include iostream -framework Cocoa " + context.filepath + " -o /tmp/objc-cpp.out && /tmp/objc-cpp.out"]
 
-  ocaml:
-    "File Based":
```
Comment (erran-r7) [inline lib/grammars.coffee]: Whoops, looks like you don't have the latest code. Please remove this part of the change making sure you pull from rgbkrk/atom-script's master branch.

File: lib/grammars.coffee [hunk 2]
```diff
@@ -200,10 +203,10 @@ module.exports =
         args: (context) -> ['-c', "xcrun clang++ -fcolor-diagnostics -Wc++11-extensions -Wall -include stdio.h -include iostream -framework Cocoa " + context.filepath + " -o /tmp/objc-cpp.out && /tmp/objc-cpp.out"]
 
   ocaml:
-    "File Based":
-      command: "ocaml"
-      args: (context) -> [context.filepath]
-
+      "File Based":
+        command: "ocaml"
```
Comment (erran) [inline lib/grammars.coffee]: Looks like some extra whitespace changes. I'll go ahead and test with these and may remove them in a later commit if you don't get to it first.

**Comment by erran** [comment]
@ThiconZ Published with [v2.20.0](https://github.com/rgbkrk/atom-script/releases/tag/v2.20.0)!
