### PR TITLE
Fix #654: missing status on killed process

### LINKED ISSUE #654: Script fails to show that program has stopped execution
In previous versions, when running a Python script, the hour glass disappeared when the process was closed either by forcing it or pressing CTRL+Q. Now the hour glass is always there, regardless of the state of the program execution. 

To reproduce, start a python application and let it finish or force close it. 

I am using Windows 7, Git 1.2.1, latest script package. Python 2.7.10 32bit. 

Whenever a python application is finished running, this is what I get:

TypeError: Cannot read property 'toString' of undefined
    at ScriptView.module.exports.ScriptView.setHeaderAndShowExecutionTime (file:///C:/Users/chw1/.atom/packages/script/lib/script-view.coffee:34:53)
    at ScriptView.setHeaderAndShowExecutionTime (file:///C:/Users/chw1/.atom/packages/script/lib/script-view.coffee:1:1)
    at file:///C:/Users/chw1/.atom/packages/script/lib/view-runtime-observer.coffee:15:13
    at Emitter.module.exports.Emitter.emit (C:\Users\chw1\AppData\Local\atom\app-1.2.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Runner.module.exports.Runner.onExit (file:///C:/Users/chw1/.atom/packages/script/lib/runner.coffee:68:14)
    at file:///C:/Users/chw1/.atom/packages/script/lib/runner.coffee:1:1
    at triggerExitCallback (C:\Users\chw1\AppData\Local\atom\app-1.2.1\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\chw1\AppData\Local\atom\app-1.2.1\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

### PR DESCRIPTION
**Pull request by rollenrolm**

### CODE REVIEW

File: lib/runtime.coffee [hunk 1]
```diff
@@ -65,11 +65,16 @@ class Runtime
...
     @runner.stop()
+    @emitter.emit 'did-execute-stop'
 
   # Public: Dispatched when the execution is starting
   onDidExecuteStart: (callback) ->
     @emitter.on 'did-execute-start', callback
 
+  # Public: Dispatched when the execution is stopped
+  onDidExecuteStop: (callback) ->
+    @emitter.on 'did-execute-stop', callback
```
Comment (rgbkrk) [inline lib/runtime.coffee]: I'd name this `stopped` or `stop` to fit better with node nomenclatures on events, but this works. If you agree, feel free to submit a follow on PR.

Comment (rollenrolm) [inline lib/runtime.coffee]: Agreed. The intention here though was to align the name with the existing codebase. So if you don't mind, i'll also change the start event/function names to reflect that and add proper pre- and post events/functions which might come in handy later.

Comment (rgbkrk) [inline lib/runtime.coffee]: Fine by me.
